### ISSUE TITLE
className error

### ISSUE THREAD

**Issue by liuw5367** [re-ovo/unocss-intellij#1]
<img width="676" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/12944473/7245bba6-a80c-4b1d-b733-4730930dc5e2">

如图，react 中使用表达式会报错。现在好像只能处理字符串类型的 className 吧

**Comment by re-ovo** [comment]
是的，没考虑到字符串模板，马山修

**Comment by re-ovo** [comment]
现在应该好了，更新下

**Comment by liuw5367** [comment]
可以了，不报错了。👍
提个建议哈，字符串模板内也应该支持提示，现在是不支持的。我用 tailwindcss 的插件字符串模板是支持提示的
