### ISSUE TITLE
不提示代码  可以显示文档

### ISSUE THREAD

**Issue by zh-neng** [re-ovo/unocss-intellij#14]
![image](https://github.com/re-ovo/unocss-intellij/assets/24434147/5c49bd0a-9faf-474f-958b-670457c46521)
![image](https://github.com/re-ovo/unocss-intellij/assets/24434147/17a5f5e5-4a30-4bd3-8860-d7ccf75499f9)
![image](https://github.com/re-ovo/unocss-intellij/assets/24434147/4ec7343e-4b5e-4e00-b39f-dc273a64e5ab)
![image](https://github.com/re-ovo/unocss-intellij/assets/24434147/0faa591b-7a60-458a-8798-5b1878a2c6ab)

**Comment by zh-neng** [comment]
这个日志在哪看 我没找到

**Comment by re-ovo** [comment]
Windows是"帮助"里:
![image](https://github.com/re-ovo/unocss-intellij/assets/21152113/d75261fc-9d5d-4cea-b01d-e59bc783a2a9)
建议随便打几个css class再传log, 方便看原因

**Comment by re-ovo** [comment]
我这测试只有1次复现了，后面就复现不了了，无语。你那是每次都这样吗？

**Comment by zh-neng** [comment]
嗯嗯  每次都这样

**Comment by zh-neng** [comment]
这个是vue2.7 每次都不提示  有个vue3的项目  打开是有提示的

**Comment by zh-neng** [comment]
我发现和unocss的版本有关系^0.53.6 可以  ^0.55.0不行

**Comment by re-ovo** [comment]
最新版依然这样吗

**Comment by zh-neng** [comment]
好像好了  我关issue了
