### ISSUE TITLE
IntelliJ with error

### ISSUE THREAD

**Issue by userquin** [re-ovo/unocss-intellij#17]
```shell
  Unhandled exception in [StandaloneCoroutine{Cancelling}@2ec82a9c, Dispatchers.IO]
  
  java.lang.RuntimeException: ENOENT: no such file or directory, unlink 'D:\work\projects\userquin\GitHub\antfu\docs\pwa-docs-vp-beta-3\__unconfig_vite.config.ts'
at me.rerere.unocssintellij.UnocssService$updateConfig$2$run$1$invokeSuspend$$inlined$sendCommand$1.invoke(UnocssProcess.kt:137)
at me.rerere.unocssintellij.UnocssService$updateConfig$2$run$1$invokeSuspend$$inlined$sendCommand$1.invoke(UnocssProcess.kt:134)
at me.rerere.unocssintellij.UnocssProcess$1$1.invoke(UnocssProcess.kt:74)
at me.rerere.unocssintellij.UnocssProcess$1$1.invoke(UnocssProcess.kt:58)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@2ec82a9c, Dispatchers.IO]
```

**Comment by re-ovo** [comment]
什么环境，什么配置

**Comment by userquin** [comment]
When using this repo: https://github.com/vite-pwa/docs

**Comment by re-ovo** [comment]
![image](https://github.com/re-ovo/unocss-intellij/assets/21152113/e85366ff-5727-4116-aa00-237c0c468b0b)
it works well for me

**Comment by re-ovo** [comment]
Is it not working at all? Or is this a coincidence?
Are you using the latest version?

**Comment by userquin** [comment]
I had 5 intellij instances opened with TypeScript projects only, the error sometimes is there and sometimes is gone.

I Will check if the plugin is still working, the error appears in the Red icon at the bottom.

**Comment by userquin** [comment]
Maybe we can just protect the code to handle missing watch files.

**Comment by re-ovo** [comment]
Does this error affect normal use? Not sure why it happened, but I guess it shouldn't affect using

**Comment by userquin** [comment]
Opening pwa docs project only  the error is missing. I guess it is about running the dev server, then stop it and finally switch to another project (the error pops up from time to time).

![imagen](https://github.com/re-ovo/unocss-intellij/assets/6311119/28ebd345-f8b1-4c33-9a00-97dfadfa1514)

**Comment by re-ovo** [comment]
@userquin can you try 1.2.2?

**Comment by userquin** [comment]
sure: I'll send you some feedback tmr, yesterday I didn't get any error from the plugin

**Comment by re-ovo** [comment]
How's it going

**Comment by userquin** [comment]
@re-ovo sorry but I'm with Android project, I'll check it next week

About the Spanish entries:
- `setting.enable=Habilitar UnoCSS` : you should use `UnoCSS` in any translation file
- `setting.autocomplete.max_items.comment=El número máximo de elementos a mostrar en autocompletar`

**Comment by re-ovo** [comment]
Hi, What about the error issue?

**Comment by userquin** [comment]
@re-ovo It seems the error is gone
