### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by xsjcTony** [re-ovo/unocss-intellij#18]
感谢这个插件！💚

---

1. 在auto-complete列表项的前面加一个图标， 比如![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/c881aca3-70bf-441b-8a41-7ad518e2044f)
就像tailwind插件那个一样，这样会很有辨识度, 同时也可以把右边`UnoCSS`的字样给去掉
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/489d808d-90ae-4a42-ae91-a3e3dfc58e38)
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/ce82a1e5-71b9-488c-9f31-b9afa63cd461)

---

2. 这种情况没有auto-complete![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/c65e3bbf-0e30-4bec-9c8c-1568b6b16505)， 感觉至少应该有 `/none` / `/tight` / `/snug` / `/normal` / `/relaxed` / `/loose`?
https://tailwindcss.com/docs/line-height

---

3. 在 `uno.config.ts` 中也提供auto-complete。有点类似于tailwind的 `tailwindCSS.experimental.classRegex`?
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/b3e77215-14b5-4c49-8225-27335f2b905a)
https://github.com/paolotiu/tailwind-intellisense-regex-list#plain-javascript-object

---

⚠️4. Provide auto-complete in theme() directive and hover doc in css / scss files

**Comment by re-ovo** [comment]
1. 图标这个，确实，主要会和颜色/icon这样的提示冲突，不过我会加上的
2. 似乎vscode那边也没有，我主要调用的它的api
3. 这个不考虑了，感觉没必要(

**Comment by re-ovo** [comment]
#2 确实是unocss那边没有返回提示，暂时不想再这边手动写规则来提供更多提示

**Comment by xsjcTony** [comment]
对我感觉2多少是有点依赖vscode那边的。。。果然。 那就算了 反正也不是啥大问题

3的话，这个东西怎么说呢就。其实也有解决办法 比如在其他有提示的地方写完再copy过来也就好了。
主要我不知道你这边是什么个逻辑，至少在`className={}`里的都会有， 不管`clsx`还是`cn`啥的都没用， 比tailwind那个破预设好多了，就其实也不是啥大问题🤣

**Comment by xsjcTony** [comment]
还有个忘记提了 挺重要的一个 当时写的时候脑子隔了一天没记起来

⚠️4. Provide auto-complete in `theme()` directive in css / scss files

**Comment by xsjcTony** [comment]
感觉 1 和 4 比较重要吧 2 3 真无所谓的🤣

**Comment by AiHMin** [comment]
> 感觉 1 和 4 比较重要吧 2 3 真无所谓的🤣

 这个 4 是相当于引用的从 unocss.config.js 那边的 theme 配置属性吗，我可以来加一下这块

**Comment by xsjcTony** [comment]
@AiHMin 对的。 和tailwind一样的用法
https://tailwindcss.com/docs/functions-and-directives#theme
https://unocss.dev/transformers/directives#theme

**Comment by AiHMin** [comment]
> @AiHMin 对的。 和tailwind一样的用法 [tailwindcss.com/docs/functions-and-directives#theme](https://tailwindcss.com/docs/functions-and-directives#theme) [unocss.dev/transformers/directives#theme](https://unocss.dev/transformers/directives#theme)

Ok, on it

**Comment by AiHMin** [comment]
Ready to review https://github.com/re-ovo/unocss-intellij/pull/20

**Comment by re-ovo** [comment]
已更新1.3.0，测试下 @xsjcTony

**Comment by xsjcTony** [comment]
感谢💚。 反馈：

_1. 图标在1080P的屏幕有点怪怪的🤣感觉是太大了 
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/7839dc85-0030-4999-81e2-866d7f4d5dc8)

_4. `theme()`似乎有问题，给的是普通的提示，不是`theme`里的内容。然后hover / Ctrl + Q 也没有预览。
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/898a7e64-53e9-4931-8b8b-dd37644a20cd)

---

unrelated: 然后今天不知道为啥整一天都没有auto-complete... 其他都是好的 不知道为啥。 刚刚升级之后好了。 如果能复现的话我再开个issue

**Comment by re-ovo** [comment]
补全那个可能是版本不匹配的问题，很莫名其妙，我只能尽量确保插件语言服务的unocss版本是最新

**Comment by re-ovo** [comment]
<img width="852" alt="截屏2023-09-04 16 53 47" src="https://github.com/re-ovo/unocss-intellij/assets/21152113/ca287db7-e9d6-46d9-82aa-ed3d8bbe70a0">
theme()我测试没问题，你怎么配置的unocss

**Comment by xsjcTony** [comment]
emm AFK了现在。 我晚点可以给份完整的。 不过我是在React工程里用的 然后是单独的scss文件里 可以试一下

**Comment by re-ovo** [comment]
是vite项目吗

**Comment by re-ovo** [comment]
可能是配置文件的寻找优先级问题，估计优先找vite配置里的设定了

**Comment by xsjcTony** [comment]
有可能 我Vite里就一个UnoCSS()就没了。我回家发一份完整的配置文件。 我看文档里说是一个单独的uno.config比较好

**Comment by re-ovo** [comment]
你可以试试在vite里加上theme测试下，应该是优先级问题

**Comment by xsjcTony** [comment]
好我回家试一下 但主要就算他没找到theme，也不应该提示正常的内容😂 所以我感觉不太像这个原因。这个theme()就是只能读theme配置里的东西的。。 奇了怪了

**Comment by xsjcTony** [comment]
Still no luck
![Snipaste_2023-09-04_20-59-12](https://github.com/re-ovo/unocss-intellij/assets/45784210/d45413a4-355c-41ed-9b5d-4d04bbc67f3b)
I've created a minimum reproduction repo

**Comment by xsjcTony** [comment]
https://github.com/xsjcTony/unocss-intellij-test
`npm install` 然后去 `/src/index.scss`里试一下. 反正我这是不行. 换了俩电脑了都是这样

**Comment by AiHMin** [comment]
> 好我回家试一下 但主要就算他没找到theme，也不应该提示正常的内容😂 所以我感觉不太像这个原因。这个theme()就是只能读theme配置里的东西的。。 奇了怪了

CSS 部分本身的 completion 逻辑是为了给 `--at-apply` 和 `@apply`  提供的，因为这两个指令可以接受 CSS string，而
`theme()` 里同样也要传入 CSS string，在 IntelliJ 平台的语法解析器都会被视为 `CssElementTypes.CSS_STRING_TOKEN`，于是就共用了这块 completion 的逻辑
我来修复一下，顺便优化下 `@screen`  的 completion 支持

**Comment by xsjcTony** [comment]
大佬顺便把图标修一下吧_(:з)∠)_整个小点的 不然全是锯齿

**Comment by xsjcTony** [comment]
@AiHMin 话说这个@apply没有 hover提示 和 下划线 是预期中的吗 还是漏掉了？
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/ada469c3-18f5-471b-899d-54a86a50722c)

详见下表

| | `@apply` | `--at-apply` |
| - |---------- | ------------ |
| auto-complete | ✅ | ✅ |
| hover preview | ❌ | ✅ |
| underline | ❌ | ❌ |

**Comment by AiHMin** [comment]
不应该，underline应该是按文件全文解析和标注的，上面那个仓库能复现吗

**Comment by xsjcTony** [comment]
可以。 我更新了代码 可以pull一下。 行为和上述表格中一致， 还是`index.scss`

**Comment by re-ovo** [comment]
<img width="680" alt="截屏2023-09-05 09 18 44" src="https://github.com/re-ovo/unocss-intellij/assets/21152113/6fc61413-0389-480e-8c8c-2ef3ddddd186">
@AiHMin 没看懂这里为什么要加这个判断

**Comment by re-ovo** [comment]
[unocss-intellij-1.3.0.zip](https://github.com/re-ovo/unocss-intellij/files/12517789/unocss-intellij-1.3.0.zip)
测试下 @xsjcTony

**Comment by xsjcTony** [comment]
咋用啊🤣

**Comment by re-ovo** [comment]
<img width="312" alt="截屏2023-09-05 09 42 01" src="https://github.com/re-ovo/unocss-intellij/assets/21152113/ce23fcfa-31d1-4fd2-9099-bbf04acbadf5">

**Comment by AiHMin** [comment]
> <img alt="截屏2023-09-05 09 18 44" width="680" src="https://user-images.githubusercontent.com/21152113/265559527-6fc61413-0389-480e-8c8c-2ef3ddddd186.png"> @AiHMin 没看懂这里为什么要加这个判断

哦，这里当时是为了保证 `XML_ATTRIBUTE` 子元素没有 `XML_ATTRIBUTE_VALUE` 只有 `XML_NAME` 来着，看来影响 CSS 部分了

**Comment by xsjcTony** [comment]
@apply 没问题了。`theme` 和 图标 没好 应该不在这里吧。

**Comment by xsjcTony** [comment]
@AiHMin 虽然我只用 `@apply`, 但是理论上这个东西是可以动态配置的： https://unocss.dev/transformers/directives#at-apply

**Comment by re-ovo** [comment]
theme没好吗？

**Comment by xsjcTony** [comment]
@re-ovo 没好 还是原来那样。可以用我上面那个小repo测试一下

**Comment by re-ovo** [comment]
<img width="491" alt="截屏2023-09-05 09 58 35" src="https://github.com/re-ovo/unocss-intellij/assets/21152113/54afcfcc-3a2f-4bac-b068-78a6611458be">
我可以啊

**Comment by AiHMin** [comment]
> @AiHMin 虽然我只用 @apply, 但是理论上这个东西是可以动态配置的： [unocss.dev/transformers/directives#at-apply](https://unocss.dev/transformers/directives#at-apply)
看到不少地方在用 --uno了。

尴尬，文档没看全🤣

**Comment by xsjcTony** [comment]
@re-ovo 这次好了欸。不知道为啥。

**Comment by xsjcTony** [comment]
我不知道背后是什么原因。。 但是感觉这些其他的似乎不应该出现在`theme`里？ 不过不太重要了
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/37ca5874-77fc-4bf3-ae28-0bc9513a95a0)

**Comment by AiHMin** [comment]
这些我正在处理，另外我可能知道为什么 theme 有时候不好了，目前 theme 只处理了直接铺平在配置文件里的情况，但实际上有可能是在同文件单独定义的变量，有可能是从外部文件导入的，需要重新考虑下取 theme 的方式

**Comment by re-ovo** [comment]
> 这些我正在处理，另外我可能知道为什么 theme 有时候不好了，目前 theme 只处理了直接铺平在配置文件里的情况，但实际上有可能是在同文件单独定义的变量，有可能是从外部文件导入的，需要重新考虑下取 theme 的方式

这个我处理了

<img width="898" alt="截屏2023-09-05 10 11 19" src="https://github.com/re-ovo/unocss-intellij/assets/21152113/ed73088e-20b7-4b51-b6fb-0d70d211c77e">

**Comment by AiHMin** [comment]
@re-ovo `theme` 你已经修了🤣

**Comment by xsjcTony** [comment]
另外还有个问题， 虽然不是啥大问题但还是告知一下比较好。
我现在在从tailwind迁移到uno，所以经常会切回tailwind的分支。
在uno分支， uno插件会启动， tailwind插件就不会出来捣乱，
但我切回tailwind分支的时候，tailwind插件正常启动， 但是uno插件也还是会工作🤣
不是啥大问题 毕竟一般也不会有这种情况
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/58c9a0bc-d830-432b-9b5a-edde7c0e2de9)

**Comment by re-ovo** [comment]
你是对的，我没有处理移除unocss的情况，主要考虑应该没人这么干

**Comment by xsjcTony** [comment]
> 你是对的，我没有处理移除unocss的情况，主要考虑应该没人这么干

那就不管了。确实一般没人会这么干。

我这边就还剩下
1. 把`theme`里那些没用的去掉
2. 图标用个小点的 防锯齿

就没了:tada:
感谢💚

**Comment by re-ovo** [comment]
这个锯齿好像没辙，我在1080p屏幕上调整了下还是糊

**Comment by re-ovo** [comment]
oh, 才发现有抗锯齿选项，没开

**Comment by xsjcTony** [comment]
nice. 那就剩去掉theme里多余的东西了, 不过无关紧要了已经.

BTW
我不太知道UnoCSS的`theme`是怎么工作的, 但他应该和tailwind是一致的, 就是用用户的theme去合并他默认的或者preset中的theme, 换言之我用tailwind的那个插件的时候, 他不止会提示用户的theme, 也会提示自带的.

举个栗子, 比如默认颜色有`red`, 我新加了一个`pink`, 然后按照现在的我可以 `colors.` 然后会有`pink`的提示, 但是就不会有 `red`. 具体的可以试下tailwind的那个插件. 
不知道这个能不能做或者方不方便. 要花很多时间也就算了

**Comment by xsjcTony** [comment]
像这些就是 `presetUno` / `presetWind` 的默认theme, 然后会把用户的theme合并进去
https://github.com/unocss/unocss/blob/main/packages/preset-wind/src/theme.ts

**Comment by re-ovo** [comment]
理论可以

> 像这些就是 `presetUno` / `presetWind` 的默认theme, 然后会把用户的theme合并进去 https://github.com/unocss/unocss/blob/main/packages/preset-wind/src/theme.ts

**Comment by AiHMin** [comment]
我加 completion 的时候想到这个事了，但是如果没在配置文件里的，倒是不会有跳转，这个应该没啥影响吧

**Comment by re-ovo** [comment]
加上这个功能了

**Comment by re-ovo** [comment]
只做了补全，文档在想怎么做

**Comment by xsjcTony** [comment]
如果你说的是autocomplete右边显示的, tailwind那个插件显示的是有几个item. 好像是 `4 values` 这种

**Comment by xsjcTony** [comment]
![Snipaste_2023-09-05_23-32-47](https://github.com/re-ovo/unocss-intellij/assets/45784210/5f6d6c17-3bd8-4307-be7a-81d2052e9e84)
...我这咋突然啥都没了

**Comment by re-ovo** [comment]
> ![Snipaste_2023-09-05_23-32-47](https://user-images.githubusercontent.com/45784210/265715051-5f6d6c17-3bd8-4307-be7a-81d2052e9e84.png) ...我这咋突然啥都没了

似乎独立css文件有问题，我看看，其他没问题了吧？图标锯齿, 多余的attributify补全

**Comment by xsjcTony** [comment]
嗯这个如果好了那就好了

**Comment by re-ovo** [comment]
[unocss-intellij-1.3.0.zip](https://github.com/re-ovo/unocss-intellij/files/12524500/unocss-intellij-1.3.0.zip)

**Comment by xsjcTony** [comment]
NB 这效率也太顶了. 都搞定了💚

**Comment by xsjcTony** [comment]
kotlin大法好
