### ISSUE TITLE
代码提示小建议

### ISSUE THREAD

**Issue by TactfulBean** [re-ovo/unocss-intellij#19]
今天才看到这个插件 用了之后确实爽❤❤❤

不过用的时候就有个问题
现在的代码提示要在第二个字母按出来之后才给出提示
能否在按第一个字母后就进行提示呢？
![65ef73fda4f2ad856b9d586534b3cfd8](https://github.com/re-ovo/unocss-intellij/assets/90669825/553e4884-f8b0-41ab-97f7-8e9337d1cce8)
![0f0ce5b42517d9f3663c34e02addb8a5](https://github.com/re-ovo/unocss-intellij/assets/90669825/99177534-ace5-4d5d-b4a8-1f33a46c15fc)
或者出个配置项来设置

**Comment by re-ovo** [comment]
已更新1.3.0，测试下

**Comment by TactfulBean** [comment]
问题解决了👍👍👍
