### ISSUE TITLE
解析带具体值的 class 错误

### ISSUE THREAD

**Issue by AiHMin** [re-ovo/unocss-intellij#2]
> 感谢大佬的插件！:rocket:

如图：
<img width="322" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/28809242/b593d1ad-ac83-4f77-8170-715f40939c9c">
正确结果应该是 `margin-left: -4px;`
参照：https://unocss.dev/interactive/?s=ml-[-4px]

**Comment by re-ovo** [comment]
fixed
