### ISSUE TITLE
[🐞Bug] Prevent underline at unwanted places

### ISSUE THREAD

**Issue by xsjcTony** [re-ovo/unocss-intellij#24]
emm 这个问题是，只要能解析成uno类名，好像基本在什么地方都会有下划线。
举几个栗子
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/479bdac6-4b9f-48e3-b183-3996ec94280a)
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/09ecab68-deb6-4976-88e0-9a619d99b1db)
上面这些就完全不该有感觉 那个 `container` 还行毕竟实在字符串里不太好判断，可能确实是用作classname的
这些只是有下划线，没有其他问题

---

然后这个attribute上的话， 感觉行为应该和之前修复的 auto-complete 保持一致， 检查是否有`presetAttributify()`
下划线和hover都不应该有，如果没有启用`attributify`的话
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/70abbb0f-a14a-4df6-8a97-a84d62d0a3b4)

💛

**Comment by AiHMin** [comment]
关于划线，目前 VSCode 的官方插件也是同样的问题，目前插件的实现逻辑都是通过把完整文件喂给 unocss 的 generator ，然后他会把所有标注好的 class，位置返回回来，然后处理，标注到 editor 里，因为考虑到 unocss 的 transformer 很多，如果手动标注划线容易不准确，因此目前的实现属于是“宁可错杀一千，不可放过一个”🤣

**Comment by xsjcTony** [comment]
🤣很有道理的样子。不懂具体是咋工作的 但是有些有下划线但没有hover info就挺奇怪的。
有upstream issue吗那边。好像没找到相关的

**Comment by re-ovo** [comment]
下划线是下划线，其他功能是其他功能，分开的，下划线激进一些，其他功能都会相对严格的匹配语法

**Comment by AiHMin** [comment]
> 🤣很有道理的样子。不懂具体是咋工作的 但是有些有下划线但没有hover info就挺奇怪的。 有upstream issue吗那边。好像没找到相关的

VSCode 插件实现起来相对容易很多，标注划线接受一个对象，设置 range，同时可以在对象里指定一个 hoverMessage getter，这样有划线就有 hover doc

但是 IntelliJ 这边不太行，annotator  只能设置 tooltip，好像没法插入富文本，文档只能分开实现
分开实现，就可能存在判断当前悬停位置不应该有 doc 或者就是漏掉没处理的情况

**Comment by xsjcTony** [comment]
👀好像有点道理。但是其他功能有严格语法匹配的话 我没懂下划线激进一些的意义在哪儿。就有点那种 “这个是unocss的类名哦 你去变量名或者属性键名换个名字”🤣

**Comment by xsjcTony** [comment]
或者to make things easy，那边我看设置里有个enable/disable下划线的功能，感觉可以跟进一下。但我又挺想要这个下划线的，可以区分uno的和自己的类名。 头疼🤦‍♀️

**Comment by yanhao98** [comment]
渲染出来也会变。

<img width="668" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/37316281/a4960b8a-68ab-48d5-bd46-793e3ae4c942">

**Comment by xsjcTony** [comment]
> 渲染出来也会变。

这个那边倒是有一样的issue https://github.com/unocss/unocss/issues/2975

**Comment by re-ovo** [comment]
> 渲染出来也会变。
> 
> <img alt="image" width="668" src="https://user-images.githubusercontent.com/37316281/265864269-a4960b8a-68ab-48d5-bd46-793e3ae4c942.png">

啥意思，没看懂

**Comment by AiHMin** [comment]
> 渲染出来也会变。
> 
> <img alt="image" width="668" src="https://user-images.githubusercontent.com/37316281/265864269-a4960b8a-68ab-48d5-bd46-793e3ae4c942.png">

@yanhao98  你是不是加了了 `@unocss/transformer-variant-group`，转换以后就是蓝色那部分
<img width="730" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/28809242/25274b30-33b6-4658-bb7e-23cc7c0dd702">

**Comment by AiHMin** [comment]
> 👀好像有点道理。但是其他功能有严格语法匹配的话 我没懂下划线激进一些的意义在哪儿。就有点那种 “这个是unocss的类名哦 你取变量名或者属性键名建议换个名字”🤣
或者to make things easy，那边我看设置里有个enable/disable下划线的功能，感觉可以跟进一下。但我又挺想要这个下划线的，可以区分uno的和自己的类名。 头疼🤦‍♀️

@xsjcTony 目前是标注逻辑是跟官方保持一致，直接移植的 VSCode 逻辑（逻辑还是比较简单粗暴的，基本是直接全文正则匹配的），看看后面官方会不会优化标注逻辑，如果那边没有计划的话，不行我再跟 @re-ovo  大佬优化一下

**Comment by xsjcTony** [comment]
> @xsjcTony 目前是标注逻辑是跟官方保持一致，直接移植的 VSCode 逻辑（逻辑还是比较简单粗暴的，基本是直接全文正则匹配的），看看后面官方会不会优化标注逻辑，如果那边没有计划的话，不行我再跟 @re-ovo 大佬优化一下

那就等官方的吧。 一般这种都是调官方API 没道理自己搞些新玩意儿的。 这问题估计vscode那边头疼的人也挺多的

**Comment by xsjcTony** [comment]
> 哦是不是 div 里的内容也被 tranformer 给转换了🤣，这是不是 uno 本身的问题？

这铁定是uno本身的问题了。连1.0都没到，等等吧

**Comment by yanhao98** [comment]
> > 渲染出来也会变。
> > <img alt="image" width="668" src="https://user-images.githubusercontent.com/37316281/265864269-a4960b8a-68ab-48d5-bd46-793e3ae4c942.png">
> 
> @re-ovo 哦是不是 div 里的内容也被 tranformer 给转换了🤣，这是不是 uno 本身的问题？

确实是 uno 本身的问题。

**Comment by xsjcTony** [comment]
upstream issue：https://github.com/unocss/unocss/issues/1581 跟这个issue本身无关了。

**Comment by zyyv** [comment]
> 渲染出来也会变。
> 
> <img alt="image" width="668" src="https://user-images.githubusercontent.com/37316281/265864269-a4960b8a-68ab-48d5-bd46-793e3ae4c942.png">

<img width="382" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/42139754/e2f48fa8-3b44-4cae-a451-55bea4b8dba7">
<img width="488" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/42139754/7c2d1580-20e2-4072-b6a2-47df0f5a49b4">

https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline  @xsjcTony 可以看看文档嘛  有解决方式

**Comment by zyyv** [comment]
我觉得此issue不是bug，只是体验优化问题吧。本身就是将全量代码喂给uno去解析的，包括里面的 ts，因为可能有人会在里面书写 动态类
```ts
const color = isRed ? 'text-red' : 'text-teal'
```
```vue
<div :class="color" />
```

**Comment by re-ovo** [comment]
我改了下高亮匹配规则，把没用的匹配过滤掉了

**Comment by xsjcTony** [comment]
> https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline @xsjcTony 可以看看文档嘛 有解决方式

@zyyv My bad. 我本身都没注意到这个问题的 主要上面有人提了。我的问题

> 我觉得此issue不是bug，只是体验优化问题吧。本身就是将全量代码喂给uno去解析的，包括里面的 ts，因为可能有人会在里面书写 动态类

字符串的我完全可以接受，并且也是合理的，但是这个 [Playground](https://unocss.dev/play/?html=DwZwxgTglgDgLgPgFAAIVgPYDsRxQMygA8BTAExQF4UBvVNdbOAQyixIgC4UByAIwDmAWgERmATyEBWAAwye9AL5JgAenDR4CIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUlCRYcNgENcdLNBAYoANRvs7MAOLauYTW1dPQABQwhjOgB6W3tHKGcoAFoANw9gLyTSPzAzJAwAD0t4TCwbLgAbEuw8QmIyAApkVChK%2BgAuOABtKlQuvQkuOhgdJNaKjD1yRDgpCuhOvVo0PTg1AF0qddk6AAtoGEGYOk7m1H1B4dG9g6O9RZhCmCSK0msnpOg7Ugw4fZSXO1HgVno8bBUzKg1LIRAoTt1enJREoVA0AJSyYTyRgsNicHh8fjozFIhSSaRNRGoOgScEYToARgAdAAmEmoCRoXCLXasMAnKJReggJl7KKQ85qDFbWSxBxOFzwnrnaxQOzyhIudyeXA%2BHLorZIKVIIA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2AEmXflnoRAL5A) 就比较离谱。没道理把 变量名 和 属性名 都一起处理的。
不过也能理解 如果要区分的话可能就要AST了。。。

**Comment by re-ovo** [comment]
等jb审核吧，已经更新上去了

**Comment by re-ovo** [comment]
更新了，测试看看

**Comment by xsjcTony** [comment]
感谢💛

> emm 这个问题是，只要能解析成uno类名，好像基本在什么地方都会有下划线。 举几个栗子 ![image](https://user-images.githubusercontent.com/45784210/265857067-479bdac6-4b9f-48e3-b183-3996ec94280a.png) ![image](https://user-images.githubusercontent.com/45784210/265857083-09ecab68-deb6-4976-88e0-9a619d99b1db.png) 上面这些就完全不该有感觉 那个 `container` 还行毕竟实在字符串里不太好判断，可能确实是用作classname的 这些只是有下划线，没有其他问题

这俩都没问题了（虽然感觉字符串里还是保留一下比较好但是不保留也合理）

> 然后这个attribute上的话， 感觉行为应该和之前修复的 auto-complete 保持一致， 检查是否有`presetAttributify()` 下划线和hover都不应该有，如果没有启用`attributify`的话 ![image](https://user-images.githubusercontent.com/45784210/265857181-70abbb0f-a14a-4df6-8a97-a84d62d0a3b4.png)

这个让他去了 毕竟是合理的。全量解析是这样的

搞定啦✨
