### ISSUE TITLE
Two suggestions for color preview blocks

### ISSUE THREAD

**Issue by fan1312** [re-ovo/unocss-intellij#27]
plugin version: 1.3.3

i. Does not reflect the effect of opacity value
e.g. `bg-black/5` and `bg-black` looks the same
![8986564715254e4ed140aa6ccdaf11a3](https://github.com/re-ovo/unocss-intellij/assets/143837928/766a73f8-54a8-4df8-b056-bb7489ca4670)

ii: I think the Block’s background color is too prominent
Maybe we can be consistent with the official, just highlight the border color instead
![f16381116f718300de768b0867b7abc6](https://github.com/re-ovo/unocss-intellij/assets/143837928/cca19aff-a481-429c-a6fc-24544bcdf2bf)

>Finally, Thanks for the plugin! 👍

**Comment by re-ovo** [comment]
1.3.4 released, you can test it

**Comment by fan1312** [comment]
v1.3.4 seems to be working, I'll close the issue
