### ISSUE TITLE
Should we make the SVG icons preview show animations?

### ISSUE THREAD

**Issue by xiaofan57** [re-ovo/unocss-intellij#28]
I used these SVG icons (https://icones.js.org/collection/svg-spinners),

![svg-spinners](https://github.com/re-ovo/unocss-intellij/assets/143837928/0f2423d6-7f73-4f4e-a3d1-8f41840ebc22)

But the existing preview effect sees a static image.
![image](https://github.com/re-ovo/unocss-intellij/assets/143837928/9fafdaee-41f0-488a-b55b-07bd9c1d0c84)

It would be great to support animated displays!

**Comment by re-ovo** [comment]
Intellij并不支持直接解析动画svg，需要手动解析动画相关属性来生成关键帧，有点麻烦了

**Comment by fan1312** [comment]
我之前有看到过这篇文章：[https://iconify.design/docs/articles/svg-animation-issues/](https://iconify.design/docs/articles/svg-animation-issues/)， 我不确定这对你解决这个问题是否有帮助
