### ISSUE TITLE
如果能点击颜色块更改颜色就更好了

### ISSUE THREAD

**Issue by T-miracle** [re-ovo/unocss-intellij#29]
如题

**Comment by re-ovo** [comment]
理论可以，但是你无法确定css name里哪个部分是颜色，因为unocss有自定义规则

**Comment by T-miracle** [comment]
> 理论可以，但是你无法确定css name里哪个部分是颜色，因为unocss有自定义规则

可以点击之后，不用自动修改class里的值，而是将颜色复制到剪贴板，至少这样会很方便😂

**Comment by T-miracle** [comment]
@re-ovo 还有就是，能否不要再class外部出现提示😂
![image](https://github.com/re-ovo/unocss-intellij/assets/44044121/2cdcdbdd-e527-4472-9ca5-84020b534ade)

**Comment by re-ovo** [comment]
> @re-ovo 还有就是，能否不要再class外部出现提示😂 ![image](https://user-images.githubusercontent.com/44044121/266838267-2cdcdbdd-e527-4472-9ca5-84020b534ade.png)

你是最新版吗

**Comment by T-miracle** [comment]
@re-ovo 
![image](https://github.com/re-ovo/unocss-intellij/assets/44044121/9ecf8369-b476-43e7-9b56-8218711391e7)
![image](https://github.com/re-ovo/unocss-intellij/assets/44044121/ba1a67d4-2cf1-48ea-99a4-79de36780322)

**Comment by re-ovo** [comment]
看看你的配置有没有启用presetAttributify
```
// uno.config.ts
import presetAttributify from '@unocss/preset-attributify'

export default defineConfig({
  presets: [
    presetAttributify({ /* preset options */ }),
    // ...
  ],
})
```
如果你启用了，它就会提示

**Comment by T-miracle** [comment]
@re-ovo 确实启用了，原来是这个问题

**Comment by re-ovo** [comment]
想了想，这个功能有点鸡肋，不做了
