### ISSUE TITLE
v1.3.4版本写代码卡顿

### ISSUE THREAD

**Issue by guoxinbao** [re-ovo/unocss-intellij#30]
当升级到这个版本时，发现写代码的时候，会有卡顿，禁用掉插件，会恢复！

**Comment by guoxinbao** [comment]
别人有这个情况吗？还是我自己哪里有问题呀

**Comment by re-ovo** [comment]
不确定

**Comment by re-ovo** [comment]
[unocss-intellij-1.3.4.zip](https://github.com/re-ovo/unocss-intellij/files/12573474/unocss-intellij-1.3.4.zip)
试试

**Comment by guoxinbao** [comment]
好像可以啦，暂时没发现卡顿了

**Comment by guoxinbao** [comment]
👍👍👍

**Comment by re-ovo** [comment]
ok
