### ISSUE TITLE
提一个小建议

### ISSUE THREAD

**Issue by niyangup** [re-ovo/unocss-intellij#32]
## 这个插件非常的棒棒
目前如果想要justify-between, 则需要按顺序输入j->u->s等才会出现, 由于顺序不是固定的, 所以需要手动按↓再选择, 
![image](https://github.com/re-ovo/unocss-intellij/assets/49631899/70878a7a-320e-4cdf-8bfd-a437a4acb0cb)
能否可以直接输入jb就出现justify-between, 就像tailwindcss插件这样
![image](https://github.com/re-ovo/unocss-intellij/assets/49631899/03ea5f59-cabf-42b2-91ee-5b823befffdb)
非常感谢

**Comment by re-ovo** [comment]
设置里可以更改匹配模式从前缀匹配为模糊匹配

Setting 》 Tools 》Unocss

**Comment by niyangup** [comment]
> 设置里可以更改匹配模式从前缀匹配为模糊匹配
> 
> Setting 》 Tools 》Unocss



已经开启模糊匹配 在输入j的时候出现插件自动完成提示弹窗, 当输入c的时候会立刻关掉 node是v16.17.0
https://github.com/re-ovo/unocss-intellij/assets/49631899/02a7da9f-5438-4e69-9dcd-cd17438a75ab

**Comment by AiHMin** [comment]
我这边好像没复现出来
<img width="513" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/28809242/5f7836c8-1e98-4846-ab68-9b28c2453cc2">

**Comment by niyangup** [comment]
清理缓存之后模糊匹配正常使用了
