### ISSUE TITLE
编写类样式时有概率卡死 webstorm

### ISSUE THREAD

**Issue by OrdinarySF** [re-ovo/unocss-intellij#33]
![image](https://github.com/re-ovo/unocss-intellij/assets/35167795/b70bf980-81df-48da-a562-06aa71dcee65)

此时无法进行任何操作，只能强制关闭WebStorm。

一般在修改某个类样式后，再修改第二个样式时发生。

强制退出后一段时间的修改不会保存。

环境：
WebStorm 2023.2.2
Build #WS-232.9921.42, built on September 12, 2023
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    AceJump (3.8.16)
    IdeaVIM (2.5.1)
    com.github.copilot (1.3.0.3323)
    me.rerere.unocss-intellij (1.3.5)

**Comment by re-ovo** [comment]
好的

**Comment by re-ovo** [comment]
更新看看呢 @OrdinarySF

**Comment by OrdinarySF** [comment]
刚刚尝试了一下没有遇到卡死的问题，如果我再使用一段时间后没有再遇到这个问题，我将关闭这个 issue 。
