### ISSUE TITLE
颜色预览透明度

### ISSUE THREAD

**Issue by TactfulBean** [re-ovo/unocss-intellij#34]
现在在编写颜色代码时确实有预览，但不知道能否对不同透明度进行适配，如下图两个颜色相同但透明度不同
![image](https://github.com/re-ovo/unocss-intellij/assets/90669825/d0289ac9-6cd8-4a9c-a4c9-7191b9e2e77f)

**Comment by liuw5367** [comment]
@re-ovo  idea 是支持在左侧行号那里显示颜色的，能否调用编辑器自带的功能进行颜色的预览呢？ 

![image](https://github.com/re-ovo/unocss-intellij/assets/12944473/7dae2f97-2122-49b8-acf3-ea45c367d60d)

![image](https://github.com/re-ovo/unocss-intellij/assets/12944473/34809d4b-dd4f-47db-8440-1f3a5f354e19)

提这个主要是因为，编辑器支持点击颜色弹出编辑框。虽然这个编辑框可能对于 unocss 来说不合适，但感觉能弹出来也是挺好的，方便查看调整色值

**Comment by re-ovo** [comment]
> @re-ovo idea 是支持在左侧行号那里显示颜色的，能否调用编辑器自带的功能进行颜色的预览呢？
> 
> ![image](https://user-images.githubusercontent.com/12944473/278799950-7dae2f97-2122-49b8-acf3-ea45c367d60d.png)
> 
> ![image](https://user-images.githubusercontent.com/12944473/278799966-34809d4b-dd4f-47db-8440-1f3a5f354e19.png)
> 
> 提这个主要是因为，编辑器支持点击颜色弹出编辑框。虽然这个编辑框可能对于 unocss 来说不合适，但感觉能弹出来也是挺好的，方便查看调整色值

unocss的颜色和类名没有强关联，我很难解析出来，这是个单向的解析操作，不能反过来

**Comment by re-ovo** [comment]
Fixed
