### ISSUE TITLE
PhpStorm 2023.2.3 安装插件后，没有提示，也没有任何的报错

### ISSUE THREAD

**Issue by simplephper** [re-ovo/unocss-intellij#37]
![微信截图_20231025172353](https://github.com/re-ovo/unocss-intellij/assets/56759640/313e8b91-7ec3-460b-b89b-54b684e0c8da)
![微信截图_20231025172403](https://github.com/re-ovo/unocss-intellij/assets/56759640/94329acf-7558-4dee-8329-f4854d359a7c)

**Comment by re-ovo** [comment]
?
