### ISSUE TITLE
在config中修改 `autocomplete`会导致 `fuzzy` / `prefix` 选项失效

### ISSUE THREAD

**Issue by xsjcTony** [re-ovo/unocss-intellij#38]
所有版本都是最新的.

我最近在写一个preset, 然后在调试的时候发现只要我更改 `autocomplete` 选项 (不管 `rules` 还是 `shortcuts`), 他就会变回 `prefix`.

我得手动切换回`prefix`再切回`fuzzy`才能让他生效.

我不确定IDE重启会不会也有这个问题, 没啥印象了.

帮忙看下, 谢谢. 感觉描述应该挺清楚了, 应该不用repo. 自己随便在`uno.config.ts`里建一个`rules`改`autocomplete`就好了

**Comment by re-ovo** [comment]
试下重启能不能解决，可能是刷新配置把match type搞没了

**Comment by re-ovo** [comment]
嗯，应该是这个问题，下个版本修复

**Comment by re-ovo** [comment]
新版本修复了
