### ISSUE TITLE
图标不提示

### ISSUE THREAD

**Issue by TactfulBean** [re-ovo/unocss-intellij#39]
今天新搭建个项目发现图标的预览没有了，打开之前的项目显示是正常的，这是什么问题
"unocss": "^0.57.6",
插件版本 1.3.8
![image](https://github.com/re-ovo/unocss-intellij/assets/90669825/4232ddc9-7672-4dbe-a22c-2fb93453a6dc)

**Comment by re-ovo** [comment]
你确定unocss配置是正确的吗？网页上能正常显示图标吗

**Comment by TactfulBean** [comment]
> 你确定unocss配置是正确的吗？网页上能正常显示图标吗

是的，网页上能正常显示

**Comment by TactfulBean** [comment]
是的，只用了@iconify-json/carbon

**Comment by re-ovo** [comment]
我测试正常

**Comment by TactfulBean** [comment]
https://github.com/TactfulBean/BeansNav-Nova
仓库地址

**Comment by re-ovo** [comment]
```
presets: [
    presetIcons(),
  ],
  ```

**Comment by TactfulBean** [comment]
这个在vite.config.ts里有写

**Comment by re-ovo** [comment]
不能混合配置

**Comment by TactfulBean** [comment]
如果不安装@unocss/preset-icons使用import presetIcons from '@unocss/preset-icons'导入，而直接import { presetIcons } from 'unocss'就没有图标提示
