### ISSUE TITLE
提供设置: 在哪些情况下显示类名和颜色等等

### ISSUE THREAD

**Issue by xsjcTony** [re-ovo/unocss-intellij#40]
举个栗子, 如果用 `shadcn/ui` 就会有这些 `cva` 中的类名:
![Snipaste_2023-11-23_14-36-41](https://github.com/re-ovo/unocss-intellij/assets/45784210/452160c5-e1b0-49ac-8e87-b9dff97938c3)
感觉得搞一下类似 `classRegex` 的东西了... 不然像上面这种情况完全就没法用T.T
![Snipaste_2023-11-23_14-40-49](https://github.com/re-ovo/unocss-intellij/assets/45784210/f2396c45-d8ee-4de8-b36e-3ecbf35a75e5)

**Comment by xsjcTony** [comment]
我现在得暂时这样子, 多少是有点抽象了🤣
![Snipaste_2023-11-23_14-42-28](https://github.com/re-ovo/unocss-intellij/assets/45784210/1593e048-f31c-4c73-a0c8-c933e7c9a36d)

**Comment by re-ovo** [comment]
Fixed
