### ISSUE TITLE
升级到2023.3 版本插件

### ISSUE THREAD

**Issue by wodabo** [re-ovo/unocss-intellij#41]
![image](https://github.com/re-ovo/unocss-intellij/assets/25549797/6eeca3e8-f836-481d-8d12-a91d8c919ad6)

**Comment by re-ovo** [comment]
[unocss-intellij-1.3.10.zip](https://github.com/re-ovo/unocss-intellij/files/13667944/unocss-intellij-1.3.10.zip)
试试，理论上应该是兼容d的
