### ISSUE TITLE
webstorm 2023.3.1 版本，鼠标放上去不显示提示框，显示类的含义

### ISSUE THREAD

**Issue by webzhouyan** [re-ovo/unocss-intellij#42]
<img width="620" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/18736886/71124613-ae27-45b6-9b94-789e79b7ba56">
如图，
**插件版本1.3.10**

**Comment by re-ovo** [comment]
怪了，是我昨天发出来的那个最新测试版吧

**Comment by webzhouyan** [comment]
> 怪了，是我昨天发出来的那个最新测试版吧

我用1.3.9版本也是这样，都是输入的时候有提示框，输完在点就没了

**Comment by re-ovo** [comment]
能否发个日志看看呢

**Comment by re-ovo** [comment]
我测试了很多项目，都是正常的，建议检查下你的日志或者unocss配置

**Comment by webzhouyan** [comment]
> 我测试了很多项目，都是正常的，建议检查下你的日志或者unocss配置

[idea.log](https://github.com/re-ovo/unocss-intellij/files/13683201/idea.log)
我重新开了一个项目也是如此这个是log,   
[ts.zip](https://github.com/re-ovo/unocss-intellij/files/13683217/ts.zip)
这个是代码
<img width="741" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/18736886/d95e3824-d8f7-4ae3-a60f-c960a242e94d">

**Comment by webzhouyan** [comment]
@re-ovo  找到问题了，webstorm设置问题
<img width="1052" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/18736886/aaddcad9-d2eb-408b-a0d7-fee08b1d2337">
需要把此项目关闭掉，有类似问题的可以参考这个
