### ISSUE TITLE
@apply 警告显示未知的规则

### ISSUE THREAD

**Issue by GGBeng1** [re-ovo/unocss-intellij#44]
<img width="331" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/40552498/e6ab756d-d66f-4e7e-89e6-6e6a5a4aa10a">
在已安装unocss插件的情况下仍然显示警告

**Comment by re-ovo** [comment]
已知问题

**Comment by re-ovo** [comment]
![image](https://github.com/re-ovo/unocss-intellij/assets/21152113/d9dd049e-579f-417f-8517-17bdcf25a4b0)
这玩意有时候没法复现，你IDE什么版本

**Comment by GGBeng1** [comment]
> ![image](https://private-user-images.githubusercontent.com/21152113/293692392-d9dd049e-579f-417f-8517-17bdcf25a4b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNDQ5NTYsIm5iZiI6MTcwNDI0NDY1NiwicGF0aCI6Ii8yMTE1MjExMy8yOTM2OTIzOTItZDlkZDA0OWUtNTc5Zi00MTdmLTg1MTctMTdiZGNmMjVhNGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAxMTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YmY3YWViZTVhZTg4NDUxNThiMWMxMTE3NDE3OGUzM2MzNGFjMDJlOTlhMzU2MDY5YjYyN2ZmZjg3MTE0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q_8GcVqKXjhywKFKMtX3xWQnbgF9gZ82ZKcXIC5DNys) 这玩意有时候没法复现，你IDE什么版本，可能是你在使用过时版本的IDE，并且插件也没法更新到最新

我现在用的是最新版本的webstrom和最新版本的插件，因为ts版本较高，现在用的volar vue服务器，我这边每次都会复现
<img width="1067" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/40552498/c55b8e9b-c3a2-43b2-b626-a25b247c5659">

**Comment by GGBeng1** [comment]
> > ![image](https://private-user-images.githubusercontent.com/21152113/293692392-d9dd049e-579f-417f-8517-17bdcf25a4b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNDQ5NTYsIm5iZiI6MTcwNDI0NDY1NiwicGF0aCI6Ii8yMTE1MjExMy8yOTM2OTIzOTItZDlkZDA0OWUtNTc5Zi00MTdmLTg1MTctMTdiZGNmMjVhNGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAxMTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YmY3YWViZTVhZTg4NDUxNThiMWMxMTE3NDE3OGUzM2MzNGFjMDJlOTlhMzU2MDY5YjYyN2ZmZjg3MTE0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q_8GcVqKXjhywKFKMtX3xWQnbgF9gZ82ZKcXIC5DNys) 这玩意有时候没法复现，你IDE什么版本，可能是你在使用过时版本的IDE，并且插件也没法更新到最新
> 
> 我现在用的是最新版本的webstrom和最新版本的插件，因为ts版本较高，现在用的volar vue服务器，我这边每次都会复现 <img alt="image" width="1067" src="https://private-user-images.githubusercontent.com/40552498/293816990-c55b8e9b-c3a2-43b2-b626-a25b247c5659.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjU3MzksIm5iZiI6MTcwNDI2NTQzOSwicGF0aCI6Ii80MDU1MjQ5OC8yOTM4MTY5OTAtYzU1YjhlOWItYzNhMi00M2IyLWI2MjYtYTI1YjI0N2M1NjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA3MDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZDdhN2Q2NjRkMmM1YTM3ZTA0ODc2NDYyZmViZTJlMTAzYTkzYTI4MGRiMGYyMmFjMWMyMWJhODcyZWIxZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uovUqT53PGXuZD5IHZKwX9hec8HPzvEfJdPDG5dwRmE">

<img width="657" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/40552498/3aaea062-bf12-4d6f-8dd4-d7badbe5a374">
使用ts原生服务就不会报警告⚠️，vue语言服务器volar时候就会报警告

**Comment by re-ovo** [comment]
明白了，Intellij SDK内部有bug会导致抑制这个错误以后会发生NPE异常，可能暂时没法修

**Comment by re-ovo** [comment]
fixed
