### ISSUE TITLE
代码提示的问题

### ISSUE THREAD

**Issue by thikiiii** [re-ovo/unocss-intellij#45]
比如我 theme  colors 里定义了 **primary**,设置背景颜色从theme取自定义的颜色，没有代码提示，设置字体颜色的时候就有代码提示

**Comment by thikiiii** [comment]
![image](https://github.com/re-ovo/unocss-intellij/assets/73383713/74d51712-c95b-4d02-b9c6-3d08549febf1)
![image](https://github.com/re-ovo/unocss-intellij/assets/73383713/5c814f93-75e1-4701-875a-d6eee820e516)
![image](https://github.com/re-ovo/unocss-intellij/assets/73383713/fdd5ab2a-5926-4fd2-8bf6-7ba459fd16e9)

**Comment by re-ovo** [comment]
![image](https://github.com/re-ovo/unocss-intellij/assets/21152113/855702a5-5ee2-4875-8a74-9469f8c08b3e)
你确定没有？多输入一个p看看，有可能排到后面去了吧

**Comment by thikiiii** [comment]
![image](https://github.com/re-ovo/unocss-intellij/assets/73383713/c725e6a5-c702-46c2-9117-672762b6ec97)
哥们我输入p的时候没有提示啦，什么提示都没有啦

**Comment by thikiiii** [comment]
![image](https://github.com/re-ovo/unocss-intellij/assets/73383713/973bcebf-94e9-492c-96d4-5e41a8e0bf06)
webstorm 版本

**Comment by thikiiii** [comment]
unocss插件的版本是最新的

**Comment by re-ovo** [comment]
bg-后面怎么可能一个都没有，再怎么也有pink purple这种吧，你怎么配置unocss的

**Comment by thikiiii** [comment]
> bg-后面怎么可能一个都没有，再怎么也有粉紫色这种吧，你怎么配置unocss的,vite内还是单独的配置文件

bg-p后面一个提示也没有，单独的配置文件

**Comment by thikiiii** [comment]
![image](https://github.com/re-ovo/unocss-intellij/assets/73383713/cb2b5978-07db-469f-9e6f-101156e398e1)
输入bg-的时候有其他的提示，但是输入bg-p的时候就没有提示了

**Comment by thikiiii** [comment]
![1704675317166](https://github.com/re-ovo/unocss-intellij/assets/73383713/6de1614e-5d8e-471f-8a12-14e0a02cd416)

**Comment by thikiiii** [comment]
![image](https://github.com/re-ovo/unocss-intellij/assets/73383713/561fd826-ebde-43a1-addc-dfacb2be6ed9)
![image](https://github.com/re-ovo/unocss-intellij/assets/73383713/00f8efd8-018d-48bd-88e1-75a1f969af25)
![image](https://github.com/re-ovo/unocss-intellij/assets/73383713/5c840d14-9204-4a63-9ad6-960c77d7f610)

**Comment by thikiiii** [comment]
> 麻烦写下presets

写那个预设？

**Comment by re-ovo** [comment]
是的

**Comment by thikiiii** [comment]
现在问题是bg-p ，就是连bg-pink 也不提示，text就提示了

**Comment by thikiiii** [comment]
![image](https://github.com/re-ovo/unocss-intellij/assets/73383713/57462de9-0983-40aa-a521-aa4b449722b8)
输入全称才会有提示

**Comment by re-ovo** [comment]
发配置...
