### ISSUE TITLE
Matcher怎么匹配字符串prop

### ISSUE THREAD

**Issue by xsjcTony** [re-ovo/unocss-intellij#48]
`.*[cC]lass[nN]ame=[\s\S]*?`

我在Matcher里加了如上的正则。。 可是为啥他匹配不了qwq `cn()`, `cva()` 倒是好了。 ant-design现在全是 `rootClassName`

![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/82bfdffb-be1a-4064-bab8-79bdbbff4cc8)

**Comment by re-ovo** [comment]
目前只能匹配JS函数
