### ISSUE TITLE
webstorm没有提示信息

### ISSUE THREAD

**Issue by guoxinbao** [re-ovo/unocss-intellij#5]
![image](https://github.com/re-ovo/unocss-intellij/assets/54174950/2f89ac46-40e4-4539-ace0-c545e98503c3)
大佬，我使用https://github.com/honghuangdc/soybean-admin项目学习一下，但是发现没有智能提示，是配置的有问题，还是其它问题呢？

**Comment by guoxinbao** [comment]
vscode 正常显示的
![image](https://github.com/re-ovo/unocss-intellij/assets/54174950/00ae7c15-a7f0-4805-a819-21dc3b266dbd)

**Comment by re-ovo** [comment]
因为默认扫描的是`unocss`依赖

**Comment by guoxinbao** [comment]
升级下最新的版本，已经解决啦！
