### ISSUE TITLE
[Feature Request] Option to truncate classes after specified length 

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [re-ovo/unocss-intellij#50]
**Describe the bug**
It's not a bug but a feature request

**How it should work**
- Plugin should truncate classes. There should be 2 options: 
1. Always
2. After specified length. 
- Classes should expand when user click inside on them
- Classes sould appear as tooltip when user hover over truncated state

**Why it's needed?**
Reduces mental complexity in the heavily styled large files

**Examples:**

**Before:**
```
class=":uno: absolute h-12 w-12 flex center rounded-full bg-black <md:(left-1/2) -translate-x-1/2"
```

**After:**
option 1: 
```
class="..."
```
option 2: 
```
class=":uno: absolute h-12 w-12 ..."
```

**Comment by re-ovo** [comment]
<img width="344" alt="截屏2024-01-17 17 24 37" src="https://github.com/re-ovo/unocss-intellij/assets/21152113/11b279de-f372-4407-b89c-b7b8195ce56a">
Code folding is already supported

**Comment by AndrewBogdanovTSS** [comment]
interesting. Could you explain how it can be enabled?

**Comment by AndrewBogdanovTSS** [comment]
Can you specify which exact option? I don't see anything specific to class names
![image](https://github.com/re-ovo/unocss-intellij/assets/2766448/c5b58660-0678-46c3-90b9-00e327ce6bb4)

**Comment by re-ovo** [comment]
![image](https://github.com/re-ovo/unocss-intellij/assets/21152113/6f5ef7b1-efc7-45d8-848a-6d1ec2f1acda)
I mean this, or use shortcut `Ctrl+Numpad-`

**Comment by AndrewBogdanovTSS** [comment]
If I understand correctly these settings only allow to manually toggle specific portions, what I'm looking for is a default behavior. When I enter a file I would like classes to be folded by default and expanded only on click. Is there a way to fold them by default in Webstorm?

**Comment by re-ovo** [comment]
I guess there is no such aggressive folding behavior in Intellij, even if the default folding is set to true, it still requires you to manually fold after editing, or reopen the file. Is that enough?

**Comment by AndrewBogdanovTSS** [comment]
Essentially, I want the same behavior for classes as for inline styles. When I open a file I see styles truncated like this
![image](https://github.com/re-ovo/unocss-intellij/assets/2766448/fdf2f5e8-86d9-49cc-bde6-53eeed46a5e5)

**Comment by re-ovo** [comment]
Sure

**Comment by re-ovo** [comment]
Will be fixed in 1.4.2, and supports some customization of folding behavior (placeholders, minimum length, default folding)

**Comment by AndrewBogdanovTSS** [comment]
Great, thanks a lot

**Comment by AndrewBogdanovTSS** [comment]
@re-ovo I tested the latest update and it looks awesome, thanks a lot for such a quick implementation and release. If I may add a couple of suggestions for improvement, it would be great if:
- clicking on the folded version would unfold only this specific item and not all in the file
- it could be a shortcut to toggle folding
- truncated text would hide classes partially, e.g. "flex pl-3 [UnoCSS]" instead of "[UnoCSS]" (don't know if this is even possible withing Intellej products)
thanks again 👍🏻

**Comment by re-ovo** [comment]
> @re-ovo I tested the latest update and it looks awesome, thanks a lot for such a quick implementation and release. If I may add a couple of suggestions for improvement, it would be great if:
> 
> * clicking on the folded version would unfold only this specific item and not all in the file
> * it could be a shortcut to toggle folding
> * truncated text would hide classes partially, e.g. "flex pl-3 [UnoCSS]" instead of "[UnoCSS]" (don't know if this is even possible withing Intellej products)
>   thanks again 👍🏻

* Collapse by group is the expected behavior, imagine that when you need to read all the code completely, you can easily expand all Unocss
* The shortcut keys are provided by Intellij. Please read the relevant documentation. On Windows, it should be
`Control` + `-`
* This can be done, but I don't think it's useful
