### ISSUE TITLE
IDE开启一段时间后，下划线消失

### ISSUE THREAD

**Issue by xsjcTony** [re-ovo/unocss-intellij#52]
**Describe the bug**
IDE开启一段时间后，下划线就消失了。
说实话不太影响使用，因为文档功能是正常的。

⚠️⚠️但是我怀疑他导致（or 冲突）了另一个问题。麻烦读一下这个：https://youtrack.jetbrains.com/issue/WEB-64982/ESLint-wont-show-red-orange-underline-after-IDE-opening-for-a-while
我观察了几次，ESLint出现这个问题每次都是下划线消失之后，所以我在想可能会不会有啥联系。
ESLint错误下划线消失这个真的要命🤣很容易miss掉一些格式错误。
最奇怪的是没有任何报错。JetBrains官方没报错，这边也没有。。就很离谱
麻烦看一下谢谢🙏

至于我为啥觉得可能是这里的问题。。因为其他不用uno的工程没碰到这个问题🤣

我存了好几包出现问题的logs，如果需要的话我还有更多
[phpstorm-logs-20240124-09404217307664289500504547.zip](https://github.com/re-ovo/unocss-intellij/files/14030605/phpstorm-logs-20240124-09404217307664289500504547.zip)

**To Reproduce**
1. Open the IDE for a while?...
2. 正常写代码？。。

**Expected behavior**
有下划线

**Screenshots**
![image](https://github.com/re-ovo/unocss-intellij/assets/45784210/330e569b-ce1c-4992-b93b-b073c79e34f2)

**Environment**
Plugin Version: latest
IDE Version: latest
Unocss Version(in package.json): latest

**Unocss Config**:
(Share your uno.config.js/ts or vite config here)
```ts
unocss({
  content: { filesystem: ['resources/views/**/*.blade.php'] },
}),
```
```ts
export default defineConfig({
  presets: [
    presetUno(),
    presetIcons(),
    presetAttributify(),
    presetRemToPx({ baseFontSize: 4 }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
});
```

**Comment by re-ovo** [comment]
高亮功能是官方调度的，这种情况我也没啥办法

**Comment by xsjcTony** [comment]
你指的是ESLint的错误下划线 还是 类名的underline？or both？
就他真的很奇怪🤣莫名其妙一段时间后 下划线就没了。然后同时ESLint的错误显示也消失了。 就除了下划线之外全部正常，然后啥也没报错。 离大谱🤦‍♀️
主要是没用uno的项目里都没这个问题。 不是这的问题的话那close吧 只能等官方那边看看了🤣

**Comment by xsjcTony** [comment]
FYI, 不只是ESLint和uno下划线消失的问题了.. 
整个ESLint错误的context从文件里消失了, 就是就算有错右上角都不显示, commit的时候也检查不出来. 估计uno的功能也被影响了. 阿巴阿巴
关键他不报错 也没什么警告 🤣 然后我也没有什么稳定reproduce的办法, 就是IDE开久了就会.... 晕掉了.
估计是官方那边啥东西出问题了, 然后官方那边又慢的一.. 😥

**Comment by re-ovo** [comment]
我都不用eslint, 这玩意对jetbrains家IDE来说完全没必要

**Comment by xsjcTony** [comment]
哈哈哈🤣我还是要的 我自己的规则集里规则太多了 https://github.com/xsjcTony/eslint-config. 原生的功能不太够.

我怀疑不止ESLint这有问题 最近IDE官方的 `JavaScript and TypeScript` 报错也很多 麻了. 感觉其他地方肯定也影响到了 等官方看看吧.

**Comment by xsjcTony** [comment]
Emm.... 没有上压力的意思 就是。。 我忍痛关了三天插件， 然后ESLint的问题就没发生过了🤣 阿巴阿巴。 至于下划线的话 毕竟插件没开所以肯定没有。

😔不知道是啥问题 没插件真有点没法写。 要是找不出问题的话怕是得去用那蠢B vscode来写有uno的项目或者用回tailwind了😭 晕了。。其他人咋没碰上这问题呢

**Comment by re-ovo** [comment]
其他功能都是正常的吧，就高亮坏了

**Comment by xsjcTony** [comment]
对。其实高亮坏了也无所谓，但是那个坏了的同时把我ESLint的整个context搞没了。。

我没说一定是这的问题😢可能不知道什么奇怪的地方冲突了。。晕了。

没办法稳定重现确实难搞，麻烦有时间帮忙找找看吧🙏🏻 找不到也无所谓 摆烂了😭 感谢

**Comment by re-ovo** [comment]
[unocss-intellij-1.4.5.zip](https://github.com/re-ovo/unocss-intellij/files/14204566/unocss-intellij-1.4.5.zip)
试试看，可能和最近的性能问题有关

**Comment by xsjcTony** [comment]
嗯我有空试试. 我反正觉得是性能问题 (I mean IDE 本身, 不是这个插件). 我在我自己的台式机(顶配)上几乎没出过问题. 就公司那笔记本 天天出这幺蛾子

**Comment by xsjcTony** [comment]
没救 还是一样. 估计就是IDE哪里出问题了. 至少官方的问题那儿, 有另一个同样的受害者了. 我把这关了吧 应该怎么都不是这的问题.
