### ISSUE TITLE
Attributify not work

### ISSUE THREAD

**Issue by Rasool-deldar** [re-ovo/unocss-intellij#53]
**Describe the bug**
I am using the @unocss/nuxt version and you wrote that you support Attributify, but the editor gives an error and I expect this error to be fixed.

![image](https://github.com/re-ovo/unocss-intellij/assets/58503211/f7e9e015-9451-4777-9105-217ce42f7f36)

And in this situation, the description does not show in the editor, please fix it

![image](https://github.com/re-ovo/unocss-intellij/assets/58503211/98002534-be7a-4974-b0ca-ef17b1a89ec7)

**Environment**
Plugin Version: 1.4.4
IDE Version: 2023.3.3
Unocss Version(in package.json): 0.58.4

**Unocss Config**:
(Share your uno.config.js/ts or vite config here)

```javascript
// uno.config.ts
import { defineConfig } from 'unocss';
import transformerDirectives from '@unocss/transformer-directives';
import transformerCompileClass from '@unocss/transformer-compile-class';

export default defineConfig({
  details: true,
  transformers: [
    transformerDirectives({
      // the defaults
      applyVariable: ['--at-apply', '--uno-apply', '--uno'],
      // or disable with:
      // applyVariable: false
    }),
    transformerCompileClass(),
  ],
});
```

**Comment by re-ovo** [comment]
Hello, please add `presetAttributify()` to you unocss config to enable attributify support

**Comment by Rasool-deldar** [comment]
> presetAttributify

This item was added in the nuxt plugin, but I installed the plugin again and added it, but these attributes are still unknown to idea

![image](https://github.com/re-ovo/unocss-intellij/assets/58503211/5854d4d9-6b22-4961-9807-8f4917bf8b1c)

**Comment by re-ovo** [comment]
will be fixed in next update

**Comment by Rasool-deldar** [comment]
> > presetAttributify
> 
> This item was added in the nuxt plugin, but I installed the plugin again and added it, but these attributes are still unknown to idea

Thank you 🌹🌹

**Comment by Rasool-deldar** [comment]
> will be fixed in next update

Thank you 🌹🌹🌹
