### ISSUE TITLE
Tagify plugin support

### ISSUE THREAD

**Issue by Rasool-deldar** [re-ovo/unocss-intellij#55]
Please support [tagify ](https://unocss.dev/presets/tagify) plugin

![image](https://github.com/re-ovo/unocss-intellij/assets/58503211/13588ce8-6884-4a64-adda-c9c5c317f9f4)

Environment
Plugin Version: 1.4.4
IDE Version: 2023.3.3
Unocss Version(in package.json): 0.58.4

Unocss Config:
(Share your uno.config.js/ts or vite config here)

```javascript
// uno.config.ts
import { defineConfig, presetUno } from 'unocss';
import presetTagify from '@unocss/preset-tagify'
import transformerDirectives from '@unocss/transformer-directives';
import transformerCompileClass from '@unocss/transformer-compile-class';
import transformerVariantGroup from '@unocss/transformer-variant-group';

export default defineConfig({
  details: true,
  presets: [
    presetUno(),
    presetTagify({ /* options */ }),
  ],
  transformers: [
    transformerDirectives({
      // the defaults
      applyVariable: ['--at-apply', '--uno-apply', '--uno'],
      // or disable with:
      // applyVariable: false
    }),
    transformerCompileClass({ classPrefix: 'chx-' }),
    transformerVariantGroup(),
  ],
});

```

**Comment by re-ovo** [comment]
ok

**Comment by re-ovo** [comment]
I will provide error suppression in next update, but no highlighting and documentation functions, because the vscode plug-in does not support it either

I recommend not using this preset, it's too aggressive
