### ISSUE TITLE
WebStorm 使用 Unocss 1.4.4 时打字卡顿问题

### ISSUE THREAD

**Issue by ytkunkun** [re-ovo/unocss-intellij#56]
## Bug 描述

在 WebStorm 中使用 Unocss 1.4.4 版本时，正常打字会出现卡顿延迟。

## 复现步骤

1. 打开 WebStorm 2023.3.3。
2. 在代码编辑器中使用 Unocss 1.4.4 版本。
3. 正常写代码并按下 Tab 键。

## 期望行为

正常写代码时，按下 Tab 键应该没有明显的卡顿或延迟。

## 实际行为

按下 Tab 键时，出现卡顿，延迟约为 0.5-1 秒。

## 系统信息

- Unocss 版本：1.4.4
- WebStorm 版本：2023.3.3

## 附加信息

禁用 Unocss 或使用 Unocss 1.4.0 版本可以避免卡顿问题。

**Comment by re-ovo** [comment]
能发下CPU性能分析日志吗, 启动这个分析器，操作一会，然后暂停，发我文件，麻烦了
<img width="686" alt="截屏2024-02-05 11 46 25" src="https://github.com/re-ovo/unocss-intellij/assets/21152113/ec6cd64d-2a64-44f0-8e67-5c4e4dac2e9e">

**Comment by re-ovo** [comment]
hello?

**Comment by guendev** [comment]
I am getting the same problem.

**Comment by re-ovo** [comment]
> I am getting the same problem.

I said, I need performance profiler report
