### ISSUE TITLE
Not working with html/pug in vue tamplate

### ISSUE THREAD

**Issue by DeniroBlack** [re-ovo/unocss-intellij#59]
We use vue js + unocss + pug 

But pug plugin not working in html/pug vue template

![image](https://github.com/re-ovo/unocss-intellij/assets/32296275/3ef9658c-4330-47d1-9203-b92dfc8270cc)

![image](https://github.com/re-ovo/unocss-intellij/assets/32296275/2b2968e3-9b97-4f8d-9591-f52fe7f6e75a)

If this could be fixed, we would be very grateful. Thanks!

**Comment by re-ovo** [comment]
Can you show me your uno config?

**Comment by DeniroBlack** [comment]
@re-ovo config is default

![image](https://github.com/re-ovo/unocss-intellij/assets/32296275/6ae8f06c-deac-498d-9788-1e2daf185f40)

**Comment by re-ovo** [comment]
I mean your unocss config, not plugin setting

**Comment by DeniroBlack** [comment]
I use unocss as vite plugin

`
import Unocss from 'unocss/vite'
import { presetAttributify, presetUno, presetWind } from 'unocss' // Presets
import { presetScalpel } from 'unocss-preset-scalpel'
import transformerCompileClass from '@unocss/transformer-compile-class'
import transformerDirectives from '@unocss/transformer-directives'
`

vite config plugin

`
Unocss({
        presets: [presetAttributify(), presetUno(), presetWind(), presetScalpel()], // Presets
        transformers: [
          transformerCompileClass(),
          transformerDirectives(),
        ]
      })
`

**Comment by re-ovo** [comment]
<img width="270" alt="截屏2024-02-28 08 47 13" src="https://github.com/re-ovo/unocss-intellij/assets/21152113/d12608a4-9a42-41a0-85cf-37874a1a8a21">
works well for me
