### ISSUE TITLE
CPU to the moon

### ISSUE THREAD

**Issue by smartrusorg** [re-ovo/unocss-intellij#60]
Hi, when i using plugin unocss, my cpu is hight to max

![image](https://github.com/re-ovo/unocss-intellij/assets/32296275/b0423fef-f8ec-435d-b256-56701201f418)

![image](https://github.com/re-ovo/unocss-intellij/assets/32296275/478e9d27-aa0d-4909-b930-7618093fb8b0)

Without unocss plugin

![image](https://github.com/re-ovo/unocss-intellij/assets/32296275/a85be1a0-1ed6-43a0-9a50-2f2225606ffd)

![image](https://github.com/re-ovo/unocss-intellij/assets/32296275/d76af9d3-e2e7-4417-883a-41baba4acab6)

Windows 11

![image](https://github.com/re-ovo/unocss-intellij/assets/32296275/89c396b8-9118-4cd2-82ea-626211054abe)

Выпуск	Windows 11 Pro
Версия	22H2
Дата установки	‎14.‎04.‎2023
Сборка ОС	22621.2283
Взаимодействие	Windows Feature Experience Pack 1000.22662.1000.0

PHPSTORM:

![image](https://github.com/re-ovo/unocss-intellij/assets/32296275/d28b0aa2-13fb-4fbe-9d22-e79356cc3c69)

PhpStorm 2023.3.2
Build #PS-233.13135.108, built on December 21, 2023
Licensed to Den Black
You have a perpetual fallback license for this version.
Subscription is active until February 6, 2025.
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 10240M
Cores: 16
Registry:
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.codeium.intellij (1.6.34)
  com.webfont.ideaplugin (3.0)
  com.github.wjlroe.idea-json-detect (1.3)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-233)
  com.jetbrains.plugins.jade (233.11799.172)

**Comment by mshamaseen** [comment]
@re-ovo, we would appreciate it if you could have a look at this, as the plugin is unusable currently because of this issue.

**Comment by re-ovo** [comment]
@mshamaseen Please provide cpu profiler report (intellij diagnostic tool)

* press  Help | Diagnostic Tools | Start CPU Usage Profiling;
* make sure that the high CPU usage problem is reproduced;
* press  Help | Diagnostic Tools | Stop CPU Usage Profiling.

The snapshot will be saved to the user home directory. Please, share this snapshot with us

**Comment by mshamaseen** [comment]
@re-ovo I tried to reproduce the issue on multiple devices and multiple projects, 2 with filesystem option points to *.blade files, and one with VueJs; they all result to high CPU usage.
Here is the diagnostic, this is a Laravel + blade + unocss project, uno config:
```
export default defineConfig({
    content: {
        filesystem: [
            'resources/forms/**/index.blade.php',
            'resources/forms/layout.blade.php',
        ]
    }
})
```
 
[PS-233.14808.18_shamaseen_13.03.2024_18.02.06.zip](https://github.com/re-ovo/unocss-intellij/files/14589627/PS-233.14808.18_shamaseen_13.03.2024_18.02.06.zip)

**Comment by re-ovo** [comment]
@mshamaseen It seems that this is a performance problem caused by initialization. Can you provide a minimum reproducible project? Because I can't reproduce it in my own project. Thanks

**Comment by mshamaseen** [comment]
@re-ovo I've sent you an invitation to our private project; it is a new project and currently is just a landing page; feel free to inspect it.

**Comment by re-ovo** [comment]
> @re-ovo I've sent you an invitation to our private project; it is a new project and currently is just a landing page; feel free to inspect it.

Tested and it still works fine on my computer

What version of Node are you using? What package management tool are you using?

**Comment by mshamaseen** [comment]
You need to open any .blade file under resources/views/**
See the following screencast that illustrate how the CPU goes up, and then it goes down when I disable uno plugin
https://github.com/re-ovo/unocss-intellij/assets/38951661/9c924999-b037-4598-894f-d8699f7fa894

**Comment by mshamaseen** [comment]
Just a note, I don't have Nodejs nor NPM installed on my device, I use docker to run my projects, so at the time of recording there is no npm or NodeJS activated
