### ISSUE TITLE
WebStorm 2024.1.2 没有提示

### ISSUE THREAD

**Issue by nomyfan** [re-ovo/unocss-intellij#63]
**Describe the bug**
试过了插件市场的1.4.7版本，也试过了自己构建1.4.8版本，都没有提示。也没看到IDE报错。

**To Reproduce**
demo项目 https://github.com/nomyfan/unocss-jbplugin-demo

**Expected behavior**

**Screenshots**
<img width="631" alt="image" src="https://github.com/re-ovo/unocss-intellij/assets/19922814/d3706ee1-2853-4799-81b9-d19c111e93d4">

**Environment**
Plugin Version: 1.4.7 and 1.4.8
IDE Version: 2024.1.2
Unocss Version(in package.json): 0.60.2

**Unocss Config**:

**Comment by re-ovo** [comment]
给我看看你配置

**Comment by nomyfan** [comment]
> 给我看看你配置

配置可以看上边贴的demo仓库

**Comment by re-ovo** [comment]
vite配置优先级大于 > uno.config.js/ts
你可以在vite配置里配置preset

**Comment by nomyfan** [comment]
还是不行。

**Comment by re-ovo** [comment]
看看配置啊

**Comment by nomyfan** [comment]
看起来不是配置的问题。我把WebStorm卸载，彻底删除缓存后重新安装好了。
