### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by vlad-borovkov** [re-ovo/unocss-intellij#66]
Hello! Could you add please or tell me how i can remove underlining css directives in WebStorm? I know that in VSCode Plugin this option is already yet.

![Скриншот_Выберите область_20240607094714](https://github.com/re-ovo/unocss-intellij/assets/95530934/715a276e-eebc-4210-82ce-2711ead9bdaf)
![Скриншот_Выберите область_20240607094741](https://github.com/re-ovo/unocss-intellij/assets/95530934/1f71bdfe-37b6-4c60-a1af-21fdfc918191)

My webStorm version is Build #WS-241.17011.90, built on May 23, 2024

**Comment by AiHMin** [comment]
I will create a PR for that
