### ISSUE TITLE
属性写法没有提示

### ISSUE THREAD

**Issue by Mophar-gift** [re-ovo/unocss-intellij#69]
**Describe the bug**
在Vue中使用时，标签上直接使用属性写法时，没有提示。
属性简写也没有下划线和提示。

**To Reproduce**
略

**Expected behavior**
属性写法也有对应的提示

**Screenshots**
![image](https://github.com/re-ovo/unocss-intellij/assets/67857649/1ff03e0b-6b40-486f-88fa-08e93632efbf)
![image](https://github.com/re-ovo/unocss-intellij/assets/67857649/c182564d-c142-4938-a87f-d0720dcc99d3)

**Environment**
Plugin Version: # 1.5.0
IDE Version: #
Unocss Version(in package.json): # 0.59.4

**Unocss Config**:
![image](https://github.com/re-ovo/unocss-intellij/assets/67857649/ba12c082-ca93-4f88-86b5-0be2a2bcd44a)

**Comment by re-ovo** [comment]
是用的vite吗

**Comment by Mophar-gift** [comment]
> 是用的vite吗

是的
"vite": "5.2.10"

**Comment by Mophar-gift** [comment]
> > > 是用的vite吗
> > 
> > 
> > 是的 "vite": "5.2.10"
> 
> 尝试直接在vite内定义配置
您好，配置哪些东西可以给一个示例吗

**Comment by re-ovo** [comment]
> > > > 是用的vite吗
> > > 
> > > 
> > > 是的 "vite": "5.2.10"
> > 
> > 
> > 尝试直接在vite内定义配置
> > 您好，配置哪些东西可以给一个示例吗，还说直接把uno.config里的配置直接在vite里配置，是这个意思吗

是的

**Comment by re-ovo** [comment]
看看你的vite配置

**Comment by Mophar-gift** [comment]
> 看看你的vite配置

![image](https://github.com/user-attachments/assets/4072b113-b7c4-4a18-9917-fbb199cf52f9)
使用类的写法是正常的有提示的，直接在标签上使用属性写法则是没有提示

**Comment by re-ovo** [comment]
我自己测试是可以的，你定义的shortcuts能正常提示吗

**Comment by Mophar-gift** [comment]
> 我自己测试是可以的，你定义的shortcuts能正常提示吗

可以发一下您的配置看一下吗

**Comment by Mophar-gift** [comment]
> 我自己测试是可以的，你定义的shortcuts能正常提示吗

鼠标移上去可以看到解析是生效的，但是在书写的时候没有任何提示
![image](https://github.com/user-attachments/assets/3be11f1a-b5dd-48e5-9dc3-bb8066975f98)

**Comment by re-ovo** [comment]
> > 我自己测试是可以的，你定义的shortcuts能正常提示吗
> 
> 鼠标移上去可以看到解析是生效的，但是在书写的时候没有任何提示 ![image](https://private-user-images.githubusercontent.com/67857649/348964423-3be11f1a-b5dd-48e5-9dc3-bb8066975f98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzQwNTMsIm5iZiI6MTcyMTEzMzc1MywicGF0aCI6Ii82Nzg1NzY0OS8zNDg5NjQ0MjMtM2JlMTFmMWEtYjVkZC00OGU1LTlkYzMtYmI4MDY2OTc1Zjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEyNDIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNWVlZjU2NDM0OGVmNTBiZDFmNzI1MzNhNmJiNzQ5ZDYwNzMzYzQ5YzlkZWQ4Y2QxZDViYzZhNDc5OTVjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dTZ9fE_7J0X69D6I3AfVl5lUYplRab85xgA_uQluWUM)

可以创建一个可以复现的项目吗，方便我测试，我自己测试没啥问题

**Comment by Mophar-gift** [comment]
> > > 我自己测试是可以的，你定义的shortcuts能正常提示吗
> > 
> > 
> > 鼠标移上去可以看到解析是生效的，但是在书写的时候没有任何提示 ![image](https://private-user-images.githubusercontent.com/67857649/348964423-3be11f1a-b5dd-48e5-9dc3-bb8066975f98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzQwNTMsIm5iZiI6MTcyMTEzMzc1MywicGF0aCI6Ii82Nzg1NzY0OS8zNDg5NjQ0MjMtM2JlMTFmMWEtYjVkZC00OGU1LTlkYzMtYmI4MDY2OTc1Zjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEyNDIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNWVlZjU2NDM0OGVmNTBiZDFmNzI1MzNhNmJiNzQ5ZDYwNzMzYzQ5YzlkZWQ4Y2QxZDViYzZhNDc5OTVjMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dTZ9fE_7J0X69D6I3AfVl5lUYplRab85xgA_uQluWUM)
> 
> 可以创建一个可以复现的项目吗，方便我测试，我自己测试没啥问题

我猜有没有可能是您对ide做了什么配置，感觉不像是项目配置的问题，为了避免其他因素干扰，我是单独新开了一个项目(pnpm create vue@latest)，项目里什么都没有，就安装了一下unocss，您可以直接尝试。
![image](https://github.com/user-attachments/assets/0fac8135-e568-471b-af6d-9a0e291e2d01)
![image](https://github.com/user-attachments/assets/e53ed11c-a92d-417d-b05e-d86869a9e298)
![image](https://github.com/user-attachments/assets/84c5763e-69aa-4fb7-9af5-77ea35868e6d)
![image](https://github.com/user-attachments/assets/693c2877-2945-487c-8437-e8cf67161801)

您可以按照我的截图随便创建一个新项目尝试一下，在任意vue文件下尝试属性写法，如果您依旧有提示，那我猜测有没有可能是您对插件做了什么配置，我本地的环境如下：
![image](https://github.com/user-attachments/assets/a595ba3e-a95a-419b-accf-ea7bb48a143d)
![image](https://github.com/user-attachments/assets/0220bdd6-78ff-4957-8b6a-2c5b867e3159)

**Comment by Mophar-gift** [comment]
您别误会我的意思哦，class里写是没问题的，我的问题一直都是在标签上直接使用属性写法：
![image](https://github.com/user-attachments/assets/4f98b1c7-7854-4e27-a773-3af94caab9c7)

**Comment by re-ovo** [comment]
我知道了，JS语言服务那边循环引用导致JSON.stringify失败了，我剔除掉没用的信息，下个版本应该可以了

**Comment by re-ovo** [comment]
更新试试

**Comment by re-ovo** [comment]
@Mophar-gift

**Comment by Mophar-gift** [comment]
更新之后可以了，感谢您的耐心解答~ (*^▽^*)

**Comment by Mophar-gift** [comment]
顺便再问一下小问题，就是在这种写法下 简写符号没有下划线
![image](https://github.com/user-attachments/assets/1f3965be-cf62-45f9-b0b3-da171805bb1f)

**Comment by re-ovo** [comment]
> 顺便再问一个小小的问题，就是在这种属性的写法下， 这种简写符号好像没有下划线 ![image](https://private-user-images.githubusercontent.com/67857649/349774974-1f3965be-cf62-45f9-b0b3-da171805bb1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzk4OTMsIm5iZiI6MTcyMTI3OTU5MywicGF0aCI6Ii82Nzg1NzY0OS8zNDk3NzQ5NzQtMWYzOTY1YmUtY2Y2Mi00NWY5LWIwYjMtZGExNzE4MDViYjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA1MTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YWE2Y2Y3NzcxNTJiNmU3OWIwNzg5MWUwODYxNTAyZTg5Nzc3MDgyZGMyZTI1MjQ4YjBiM2IyNmEwMWVhNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BVxiDvjWUqKtzawmdp7Qx4BKkdiNzD2voZkvemqhGs)

开个新issue
