### ISSUE TITLE
--at-apply：能否给出代码提示？

### ISSUE THREAD

**Issue by yys730** [re-ovo/unocss-intellij#7]
css中 --at-apply：后面输入的时候，能否像html里输入时一样，给出代码提示？

**Comment by re-ovo** [comment]
vscode那边也没有提示 🫤

**Comment by yys730** [comment]
啊？vscode我这边看倒是有的

**Comment by re-ovo** [comment]
那个好像只是提供文档和高亮，补全我测试没有

目前我这边的代码办不到在css里实现这些功能，可能需要重构了

**Comment by yys730** [comment]
好的，目前的功能已经提供了很大的便利，非常感谢~
