### ISSUE TITLE
关于属性写法符号未识别的问题

### ISSUE THREAD

**Issue by Mophar-gift** [re-ovo/unocss-intellij#70]
如下图所示，简写符号未被识别，缺少下划线提示。

![image](https://github.com/user-attachments/assets/417faff1-ef89-426b-a86b-c6f5c8f37f31)

**Comment by AiHMin** [comment]
正好我这攒了点 PR，顺手一起修了吧 @re-ovo

**Comment by re-ovo** [comment]
> 正好我这攒了点 PR，顺手一起修了吧 @re-ovo

豪德
