### ISSUE TITLE
类名提示一直显示fetching document

### ISSUE THREAD

**Issue by feixue-tech** [re-ovo/unocss-intellij#71]
**使用webstorm或gateway远程开发时类名无法提示 无代码补全提示**

本地开发时可以正常使用,远程开发时异常，而且会导致webstorm卡顿,能否修复下
远程环境系统版本debain12  webstorm 2024.1.5 

**Screenshots**
![image](https://github.com/user-attachments/assets/dcc044a2-a5d4-4339-8695-f3bd4c5b5c9c)

**Environment**
Plugin Version: #1.5.1
Webstorm Version: # 2024.1.5
Unocss Version(in package.json): # 0.61.5

**Unocss Config**:
export default defineConfig({
    presets: [
        presetUno(),
    ],
})

**Comment by re-ovo** [comment]
2024.1远程开发调用node有问题，可以试试2024.2 EAP

**Comment by re-ovo** [comment]
duplicated with #68
