### ISSUE TITLE
升级到WebStorm2024.1.5后，unocss属性不显示下划线了

### ISSUE THREAD

**Issue by zhouyusd** [re-ovo/unocss-intellij#72]
**Describe the bug**
升级到WebStorm2024.1.5后，unocss属性不显示下划线了

**To Reproduce**
我也不知道咋复现，我升级完Webstorm就这样了

**Expected behavior**

**Screenshots**
![Snipaste_2024-07-21_13-05-11](https://github.com/user-attachments/assets/57587045-75fe-4b04-977b-5045e2dd69eb)

**Environment**
Plugin Version: 1.5.1
IDE Version: Webstorm 2024.1.5
Unocss Version(in package.json): 0.61.2

**Unocss Config**:
```typescript
import { defineConfig, presetUno, presetAttributify } from "unocss";

export default defineConfig({
  presets: [presetUno(), presetAttributify()]
});
```

**Comment by re-ovo** [comment]
我没问题啊, 发下IDE日志看看呢
![QQ_1721541610681](https://github.com/user-attachments/assets/e5ee4542-4769-45d4-bb5b-9facdc17de67)

**Comment by zhouyusd** [comment]
抱歉啊，刚试了一下又好了，我也不知道为什么，中午确实不显示，配置的东西也不起作用，右下角报告了很多异常，但不小心给清除了，现在没问题了，可以正常显示了，配置也起作用了。
