### ISSUE TITLE
question: is icon suggestion/auto-completion supported?

### ISSUE THREAD

**Issue by userquin** [re-ovo/unocss-intellij#74]
![image](https://github.com/user-attachments/assets/33eb521e-e544-4890-b9ed-ca952b0beea6)

**Comment by re-ovo** [comment]
Sorry, there is no icon completion at the moment. There is no icon completion in vscode either. It is implemented through another plugin. The unocss language service does not provide icon completion. I will consider implementing one myself.

**Comment by userquin** [comment]
> There is no icon completion in vscode either.

No, VSCode works: https://github.com/vuetifyjs/vuetify/pull/20266#issuecomment-2265159762

**Comment by re-ovo** [comment]
Yes, you need a seprate plugin for it [Iconify IntelliSense](https://marketplace.visualstudio.com/items?itemName=antfu.iconify)

**Comment by userquin** [comment]
upps, you're right

**Comment by userquin** [comment]
I'll try to add it...

**Comment by userquin** [comment]
Uhmm, your graddle loading files only present in your local, you should fix this, it is only when relasing the plugin:

![image](https://github.com/user-attachments/assets/c04f3c15-fadd-424c-af62-3dfcd37b4e44)

**Comment by re-ovo** [comment]
> Uhmm, your graddle loading files only present in your local, you should fix this, it is only used when releasing the plugin:
> 
> ![image](https://private-user-images.githubusercontent.com/6311119/354608847-c04f3c15-fadd-424c-af62-3dfcd37b4e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDU0MDAsIm5iZiI6MTcyMjYwNTEwMCwicGF0aCI6Ii82MzExMTE5LzM1NDYwODg0Ny1jMDRmM2MxNS1mYWRkLTQyNGMtYWY2Mi0zZGZjZDM3YjRlNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTMyNTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQwZDQxZWU4ZTQ3YTg0YzdlMjUwMmE3OGU2MzZjNjEwZTBjYzliYmQ3YTI5YjVkZGYyZjZlMTQ1ODJhNGY0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MtE-Q1WIg7s9p4NtZVzNuofb_z9tW0BHOp4Tpwcq4Is)

If you are just developing, you should not need these files

**Comment by re-ovo** [comment]
Will be fixed in next version

**Comment by re-ovo** [comment]
released

**Comment by userquin** [comment]
Cannot analize package dependencies? The full iconify json is huge and you will need to release a new version on every iconify json release.

**Comment by re-ovo** [comment]
> Cannot analize package dependencies? The full iconify json is huge and you will need to release a new version on every iconify json release.

You are right, there may be a better way to load it

But I think icons don't need to be updated frequently, even if some icons are missing, it shouldn't matter, and there is no need to update with iconify
