### ISSUE TITLE
wxml中没有语法提示

### ISSUE THREAD

**Issue by hongdapi** [re-ovo/unocss-intellij#76]
WebStorm 2024.1.4
插件版本 1.7.0

![image](https://github.com/user-attachments/assets/0348af86-b31d-4707-b306-902630944f7b)

![image](https://github.com/user-attachments/assets/c34a4e28-b7e9-4888-bd96-b6bedef582a5)

**Comment by re-ovo** [comment]
已支持，更新试试

**Comment by hongdapi** [comment]
> 已支持，更新试试

现在可以了，感恩，感觉可以加个匹配文件后缀的设置项，没时间的话就算了
