### ISSUE TITLE
IDE警告: 此处不允许使用特性 w / h

### ISSUE THREAD

**Issue by MidnightCrowing** [re-ovo/unocss-intellij#78]
想问一下, 这个算是bug吗?
![PixPin_2024-08-10_21-19-54](https://github.com/user-attachments/assets/30dc82d1-273c-4e85-b0f5-dcd080031ad4)

插件版本: 1.7.1

**Comment by re-ovo** [comment]
我个人不是很推荐用attributify

**Comment by MidnightCrowing** [comment]
我看了一下，1.7.4 好像没有这个问题了
