### ISSUE TITLE
请问为什么webstorm中的unocss 插件有提示，却没有对应的具体解释？

### ISSUE THREAD

**Issue by zhgtt** [re-ovo/unocss-intellij#79]
**Describe the bug**
请问为什么webstorm中的unocss 插件有提示，却没有对应的具体解释？

**To Reproduce**
我的项目是 vite5 + vue3
出现这个情况，请问我还需要配置什么吗？

![image](https://github.com/user-attachments/assets/31bd772d-63e9-4224-9676-90663ba7af0b)

**Comment by re-ovo** [comment]
现在通过侧边预览来显示
<img width="1021" alt="截屏2024-08-12 16 48 41" src="https://github.com/user-attachments/assets/00d1a9bd-f0e9-44f5-8d2a-5079c929ddc1">

**Comment by zhgtt** [comment]
不好意思，我这个侧边栏也是没有任何提示的。。卸载了重新安装也没有，unocss 插件版本1.7.1，webstorm 版本是2024.1

**Comment by WiseSheep1** [comment]
@re-ovo 行内提示能通过配置显示吗，侧边预览有些占用空间
