### ISSUE TITLE
非常卡，打字的时候直接CPU 100%

### ISSUE THREAD

**Issue by DoveAz** [re-ovo/unocss-intellij#82]
**Describe the bug**
非常卡，已经是最新版了，配置足够，cpu 13700kf，64G内存, 然后我删除了这个插件，又重新装了一下，似乎不卡了，有没有可能是老版本插件的缓存会影响到新版本

**To Reproduce**
随意打开一个unocss项目，在class里面按一下或几下空格 cpu就暴涨100%

**Expected behavior**
不卡

**Screenshots**

**Environment**
Plugin Version: 1.73 
IDE Version: 2024.2.1
Unocss Version(in package.json): 0.62.0

**Unocss Config**:
// uno.config.ts
import {
  defineConfig,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  shortcuts: [
    {
      card: 'shadow-card rounded-lg p-3',
    },
  ],
  theme: {
    colors: {
      primary: '#2CCE9C',
      success: '#00B86E',
      danger: '#F34F5A',
      warning: '#F6CD5B',
      gold: '#F6CD5B',
      'gray-b': '#BEC6C8',
      'gray-a': '#A8B4B7',
      'gray-8': '#89999D',
      'gray-3': '#333333',
    },
    boxShadow: {
      card: '0 2px 5px 1px rgba(81, 96, 91, 0.4)',
    },
  },
  presets: [
    presetUno(),
    presetIcons(),
    presetTypography(),
    presetWebFonts({
      fonts: {
        // ...
      },
    }),
  ],
  transformers: [transformerDirectives(), transformerVariantGroup()],
})

**Comment by re-ovo** [comment]
![image](https://github.com/user-attachments/assets/8b2379a7-1f9d-4be4-b224-2a4a363ba1d7)
麻烦提供下性能分析报告
开启之后用1分钟然后停止，发我那个文件

**Comment by DoveAz** [comment]
> ![image](https://private-user-images.githubusercontent.com/21152113/361155979-8b2379a7-1f9d-4be4-b224-2a4a363ba1d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NjQzNDAsIm5iZiI6MTcyNDU2NDA0MCwicGF0aCI6Ii8yMTE1MjExMy8zNjExNTU5NzktOGIyMzc5YTctMWY5ZC00YmU0LWIyMjQtMmE0YTM2M2JhMWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDA1MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2Y2IxMGMyOTU0ZmU3YTc4NDJkMTVjOTRhYWZmNjNjNWE3OWNmNGI0NTQzZjk1YjM1Y2RiM2RlNjU2MDBlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6vL30Hvff3qhcixmwVx6KeYFnn75bjOl-201odjPKjE) 麻烦提供下性能分析报告 开启之后用1分钟然后停止，发我那个文件

2024.2.1 似乎没这个按钮了。。
另外我又做了一些尝试，即使完全关闭 unocss，打字的时候仍然CPU占用很高，这可能还是 webstorm 本身的性能问题
