### ISSUE TITLE
未显示转换为px的效果

### ISSUE THREAD

**Issue by lanrenbulan** [re-ovo/unocss-intellij#86]
未显示转换/* 16px */ 的效果
![image](https://github.com/user-attachments/assets/d05ae229-b25e-44b5-a7f8-4e66ae9c5a27)

插件版本: 1.7.3
webstore版本： WebStorm 2024.2.4 / Build #WS-242.23726.96, built on October 22, 2024

**Comment by winlans** [comment]
phpstorm也是如此

**Comment by winlans** [comment]
已安全最新版 1.7.4 还是无法正常展示px  

版本 WebStorm 2024.2.3

@re-ovo

**Comment by re-ovo** [comment]
1.7.5已修复

**Comment by winlans** [comment]
@re-ovo 酷，已经更新到最新版，很棒😃
