### ISSUE TITLE
web storm 2024.3 bug 弹窗一直在后台加载会打开几千个

### ISSUE THREAD

**Issue by InfernalAzazel** [re-ovo/unocss-intellij#90]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/bcc3ca03-08d6-48bd-b734-9be652a4c321)

**Environment**
Plugin Version: # 
IDE Version: #
Unocss Version(in package.json): #

**Unocss Config**:
(Share your uno.config.js/ts or vite config here)

**Comment by re-ovo** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![image](https://private-user-images.githubusercontent.com/40333954/389359321-bcc3ca03-08d6-48bd-b734-9be652a4c321.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTA2NzcsIm5iZiI6MTczMjUxMDM3NywicGF0aCI6Ii80MDMzMzk1NC8zODkzNTkzMjEtYmNjM2NhMDMtMDhkNi00OGJkLWI3MzQtOWJlNjUyYTRjMzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA0NTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZTFlMTgyZmQ4MDAwY2UxN2NlMjIyMDhhNDBjZWRmM2VhYTE5MWNjOTE0ZjFmZWQ1MzVmYTUwMGY5YWI4NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eXcw0vFg0AtZqlybkgcIClKwTp3pdIK0eHzOeLmnsY4)
> 
> **Environment** Plugin Version: # IDE Version: # Unocss Version(in package.json): #
> 
> **Unocss Config**: (Share your uno.config.js/ts or vite config here)
请提供下信息
1. 是否是使用WSL开发
2. Node版本(`node -v`)
3. IDE日志 (idea.log)

**Comment by InfernalAzazel** [comment]
找到原因了，环境有 v12 和 v20版本的node，由于idea 没有识别到就会触发这个异常。

需要再idea 上设置 node v20版本则正常运行。

![image](https://github.com/user-attachments/assets/fa07deae-1adf-4f65-983b-b0e0972059b2)
